### ISSUE TITLE
Feature request: to create a PR with a label

### ISSUE THREAD

**Issue by oscard0m** [gr2m/octokit-plugin-create-pull-request#102]
Would it be possible to extend this plugin to give support to creating a PR with a label?

Relates to https://github.com/wolfy1339/octoherd-script-remove-eol-node-versions/issues/3

**Comment by gr2m** [comment]
Sure, we can add a `.labels` option that can be set to an array of label names?

**Comment by wolfy1339** [comment]
The endpoint accepts multiple labels as an array when using `@octokit/request`, it makes sense to follow that

**Comment by oscard0m** [comment]
> The endpoint accepts multiple labels as an array when using `@octokit/request`, it makes sense to follow that

I'm a bit confused with `labels` parameter:
- Checking `@octokit/rest`[^1][^2], `labels` does not appear as a property of `Options`
   - but I see it in the `README.md` [here](https://github.com/octokit/request.js#features)
- In [GitHub Docs](https://docs.github.com/en/rest/pulls/pulls#create-a-pull-request) I don't see `labels` as an option when creating a Pull Request
   - But I just remembered [_Pull Requests_ can be treated as _Issues_](https://docs.github.com/en/rest/issues/issues#list-issues-assigned-to-the-authenticated-user) as well.
       - But [playing around with Octokit](https://stackblitz.com/edit/node-dnzjxx?file=index.mjs) I only get `issues`, not `PRs + issues`
   - And [GitHub's cli](https://github.com/cli/cli) offers creating a `pr` with `labels` (`gh pr create --label label1,label2,label3`) so I'm assuming is possible.

It's GitHub's Documentation wrong or our types are wrong? Or there is something I'm not understanding.

---

- [^1]: [`@octokit/request.js` README](https://github.com/octokit/request.js#features)
- [^2]: [TypeScript Playground using `octokit.request()` with `labels`](https://www.typescriptlang.org/play?ts=4.6.4#code/JYWwDg9gTgLgBAbzlApgRwK4oM7wL5wBmUEIcA5AAIQDGMEA1sDAPSqY4zkDcAULzCgBPRLzhwaEAHa5kODABt4AXjgBDAO5rmcjrgAU+gEQAFAPIBlACpw2KSNhYIIGqSih4nqSJ7CKF2EYAlAA0iHBi4nAublAAXHBGRiGR4t4QCUkpUXAKagBGKAEJUv7ZUQAWKGoAJpnJqXD5atgo9ZF4QXyRkjIQCigAdAoQAOb6qNiKMF28BDRqMDQV+ihBouK92P1D7iRQq7N4QA)

**Comment by gr2m** [comment]
> * And [GitHub's cli](https://github.com/cli/cli) offers creating a `pr` with `labels` (`gh pr create --label label1,label2,label3`) so I'm assuming is possible.

it's probably two requests

> * but I see it in the `README.md` [here](https://github.com/octokit/request.js#features)

The request is not to create a pull request, the example is showing `POST /repos/{owner}/{repo}/issues/{number}/labels`

**Comment by oscard0m** [comment]
> > * but I see it in the `README.md` [here](https://github.com/octokit/request.js#features)
> 
> The request is not to create a pull request, the example is showing `POST /repos/{owner}/{repo}/issues/{number}/labels`

🤦🏽 I misread it.
