### ISSUE TITLE
Editing GitHub actions does not work

### ISSUE THREAD

**Issue by cursedcoder** [gr2m/octokit-plugin-create-pull-request#104]
So every time you edit/create/do whatever with `.github/workflows/something.yml`, the API will always respond 404.

It mostly looks like something on GitHub side preventing creating such git trees.

Here are some SO threads with the same problem:

https://stackoverflow.com/questions/68086815/how-to-create-git-tree-with-nested-directories
https://stackoverflow.com/questions/68071992/how-to-commit-a-folder-and-open-a-pull-request-via-github-api

**Comment by cursedcoder** [comment]
Okay, so this seems to be a security thing.

Your PAT needs a workflow scope added, otherwise GitHub doesn't allow to change these files.
<img width="515" alt="image" src="https://user-images.githubusercontent.com/899452/179355630-e920710d-58a2-4fd3-999a-572488e23102.png">

**Comment by gr2m** [comment]
> so this seems to be a security thing

correct 👍🏼
