### ISSUE TITLE
Opening a PR with many `File`s takes ~10m

### ISSUE THREAD

**Issue by rmartine-ias** [gr2m/octokit-plugin-create-pull-request#121]
If a project sends many [`type: File`](https://github.com/gr2m/octokit-plugin-create-pull-request/blob/10e9a309ce5f21a0ab9ef3d2372c5d927f9ebc83/src/types.ts#L32)s to `createPullRequest`, it calls [`createTree`](https://github.com/gr2m/octokit-plugin-create-pull-request/blob/10e9a309ce5f21a0ab9ef3d2372c5d927f9ebc83/src/compose-create-pull-request.ts#L103), which [runs](https://github.com/gr2m/octokit-plugin-create-pull-request/blob/db6b15fa1522a2426b88edbd0c20041065a33776/src/create-tree.ts#L24) a `Promise.all` on `Object.keys(changes.files)` (it makes a new promise for each file passed to it, and fires them all at the same time, if I understand correctly). Each `Promise` [calls](https://github.com/gr2m/octokit-plugin-create-pull-request/blob/db6b15fa1522a2426b88edbd0c20041065a33776/src/create-tree.ts#L81) `valueToTreeObject`. Annotated and condensed:

```javascript
export async function valueToTreeObject(
  ...
  value: string | File // It's a File!
) {
  ...
  if (typeof value === "string") {
    // Nope!
  }
  
  // This is what gets called!
  const { data } = await octokit.request(
    "POST /repos/{owner}/{repo}/git/blobs",
    {
      owner,
      repo,
      ...value,
    }
  );
  ...
}
```

So this is POSTing to GitHub for every file, concurrently. This takes a long time to complete -- so long that the project where I found this issue in [disables](https://github.com/backstage/backstage/pull/13506) respecting GitHub's rate limits. This unfortunately means that it will sometimes hard fail on a secondary rate limit, if there are too many files.

I think there must be another way to do this that does not make an API request once per file.

(Original issue from project using this library: https://github.com/backstage/backstage/issues/17188)

**Comment by gr2m** [comment]
> I think there must be another way to do this that does not make an API request once per file.

I would recommend to use https://github.com/octokit/plugin-throttling.js, or simply use the `octokit` package which has it enabled by default. It prevents you from hitting the rate limits as much as possible, and handles the situation when it does.

Mutating requests are limited to 1/s. So if you have a lot of files to create, it will take a while.

does that help?

**Comment by stefanbuck** [comment]
This might be solved by https://github.com/gr2m/octokit-plugin-create-pull-request/pull/128 or at least defer the issue to really big PRs

**Comment by rmartine-ias** [comment]
@gr2m :

> does that help?

Unfortunately not; using the throttling plugin fixes hitting the API limits, but does not fix the amount of time taken. This is why the upstream project I am using disabled throttling for their use case.

> So if you have a lot of files to create, it will take a while.

All I know is that somehow, this is not an issue when using the `git` binary to push. And it does not make sense to me that there should be a limit of 1/second for such a critical task as "uploading a file". So it must be possible to do this faster while respecting API limits. I am not sufficiently well versed in git internals to understand how, unfortunately. Maybe you can [create the blobs locally](https://github.com/git/git/blob/master/builtin/hash-object.c), and [send a full tree](https://docs.github.com/en/rest/git/trees?apiVersion=2022-11-28#about-git-trees)?

**Comment by gr2m** [comment]
If it takes too much time, then using Octokit is not the right option for you. There is no way around the rate limiting, they are there for good reason.

You'll have to checkout the repository using `git`, do your changes in a new branch, and push the changes to the remote branch, then only create the pull request with octokit based on the branch.

I'm sorry that I can't help you better.

**Comment by rmartine-ias** [comment]
Thank you for looking at this! I read a bit deeper and you are definitely right -- with the GitHub API, there is no way to batch-upload binary files. I think the fix is to change the usage of the plugin in the project I linked to send `string`s instead of base64 encoded `File`s when possible.

Something I was wondering though -- is it possible to treat `utf-8` `100644` `File`s as text files, rather than binary? It looks to me like the they are identical to `string`s, and this would avoid calling the create blob endpoint for those. It would let users of the plugin do a pattern like [this](https://github.com/backstage/backstage/blob/391b7fbd28405d00b38769867b5cd4a7973ebcbf/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/githubPullRequest.ts#L273), where they send everything as `File`s, some of them `base64` and most of them `utf-8`, easily.

**Comment by gr2m** [comment]
> is it possible to treat `utf-8` `100644` `File`s as text files, rather than binary

Yes, there is this API:
https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#create-or-update-file-contents

But it would create a separate commit for each file you create/update which we don't want in the context of this plugin. And I think the size limits are lower for this endpoint compared to the git APIs, but maybe that is no longer the case, I don't see it in the docs.

**Comment by rmartine-ias** [comment]
Ah, I think I may have explained what I was thinking poorly. Definitely don't want to create a commit for each file. What I meant was, would something like this work?

```diff
diff --git a/src/value-to-tree-object.ts b/src/value-to-tree-object.ts
index 67ff98b..48b4940 100644
--- a/src/value-to-tree-object.ts
+++ b/src/value-to-tree-object.ts
@@ -8,7 +8,8 @@ export async function valueToTreeObject(
   path: string,
   value: string | File
 ) {
-  let mode = "100644";
+  const defaultMode = "100644";
+  let mode = defaultMode;
   if (value !== null && typeof value !== "string") {
     mode = value.mode || mode;
   }
@@ -22,6 +23,14 @@ export async function valueToTreeObject(
     };
   }
 
+  if (mode === defaultMode && value.encoding === "utf-8") {
+    return {
+      path,
+      mode: mode,
+      content: value.content,
+    };
+  }
+
   // Binary files need to be created first using the git blob API,
   // then changed by referencing in the .sha key
   const { data } = await octokit.request(
```

**Comment by gr2m** [comment]
I'm not sure, it's been a while since I worked with these APIs. Can you give it a try? Happy to implement the optimization if it doesn't break anything else

**Comment by rmartine-ias** [comment]
Will do!

**Comment by rmartine-ias** [comment]
Looks like it works. Changes here: https://github.com/gr2m/octokit-plugin-create-pull-request/compare/main...rmartine-ias:octokit-plugin-create-pull-request:utf-8-optim

The fixture update is a bit of a mess but I'm not sure if I can do it better. I can make a PR with the changes if they're something you'd want.

With the changes, this code:

```typescript
  const pr = await octokit.createPullRequest({
    owner: "rmartine-ias",
    repo: "gr2m-sandbox",
    title: "One comes, one goes",
    body: "because",
    head: "test-branch-" + Math.random().toString(36).substr(2, 5),
    changes: {
      files: {
        "path/to/file1.txt": "Content for file1",
        "path/to/file2.txt": "Content for file2",
        "small.gif": {
          content: "R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=",
          encoding: "base64",
          mode: "100644",
        },
        "small-noencode.gif": {
          content: "R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=",
          encoding: "base64",
        },
        "path/to/file5.sh": {
          content: "echo Hello World",
          encoding: "utf-8",
          mode: "100755",
        },
        "another-file.txt": {
          content: "I have content, ergo I am content",
          encoding: "utf-8",
          mode: "100644",
        },
        "another-file-no-mode.txt": {
          content: "I have content, ergo I am content",
          encoding: "utf-8",
        },
      },
      commit: "why",
    },
  });
```

Makes this PR: https://github.com/rmartine-ias/gr2m-sandbox/pull/30/files

It handles binary files, utf-8 files, and non-default modes on utf-8 files successfully.

**Comment by gr2m** [comment]
Cool I'll have a look thank you
