### ISSUE TITLE
Prompts gets eaten

### ISSUE THREAD

**Issue by stefanbuck** [gr2m/octokit-plugin-create-pull-request#126]
I'm attempting to wrap this library in a CLI. Thanks to its well-designed API, I made really good progress. However I encountered a problem and solving this would require a change in the library itself.

The idea is to wrap all `changes.files` values in a function to allow the CLI to prompt a confirmation dialog for each diff. This works if there is only one file change per diff and users of the CLI can accept or reject individual changes. 

![](https://github.com/gr2m/octokit-plugin-create-pull-request/assets/109112986/c5497453-2aac-451c-a708-9721471ad874)

But if you have multiple files this doesn't work and only the last prompt becomes active.

![](https://github.com/gr2m/octokit-plugin-create-pull-request/assets/109112986/e61fb803-d73a-47c4-81d4-6ab5c0ff893f)

The desired behaviour would be

![](https://github.com/gr2m/octokit-plugin-create-pull-request/assets/109112986/921d06dc-4acd-4495-9f74-201cd341da7b)

I was able to narrow the problem down to https://github.com/gr2m/octokit-plugin-create-pull-request/blob/main/src/create-tree.ts#L19 The `Promise.all` will resolve all promises at the same time which seems to not work well with stdin. I can see why this was implemented in the first place like that to allow parallel execution of all the promises to speed up the overall process. 

The potential fix would be to rewrite this line (or make it somehow configurable) to use a `for-of loop` instead of `Promise.all`

```diff
 for (const path of Object.keys(changes.files)) {
```
along with some modifications to the various return calls. 

As said, making this the default behaviour would change the performance characteristics of this library. Putting this behind a flag should be possible but having two code paths for this feels not ideal. Maybe there is a third option I'm not aware of.

**Comment by gr2m** [comment]
> `changes.files` values in a function to allow the CLI to prompt a confirmation dialog for each diff

sounds like a great change. I don't mind having files changed one-by-one. In most common use cases, mutating requests should be throttled anyway.
