### ISSUE TITLE
Allow programmatic file deletion

### ISSUE THREAD

**Issue by stefanbuck** [gr2m/octokit-plugin-create-pull-request#129]
The current API design supports just a single way of deleting a file

```js
files: {
  "file/to/delete.txt"" null
}
```

However, it would be useful to trigger a file deletion based on specific conditions, such as the example below:

```js
files: {
  "file/to/delete.txt": ({ exists, encoding, content }) => {
    // do not create the file if it does not exist
    if (!exists) return null;

    const fileContent = Buffer.from(content, encoding).toString("utf-8")

    if (fileContent.includes('abc')) {
      // trigger file deletion
      return ???
    }

    // do not alter file content
    return null;
  }
}
```

Since both `null` and `undefined` already have different functionalities, it is unclear what return value could be used to instruct the library to initiate a file deletion. What are your thoughts?

**Comment by gr2m** [comment]
> Since both `null` and `undefined` already have different functionalities, it is unclear what return value could be used to instruct the library to initiate a file deletion. What are your thoughts?

I think the correct way to do this is to use Symbols. See how `mapObjectSkip` is implemented in [map-obj](https://github.com/sindresorhus/map-obj). I don't mind releasing a breaking change for this.

What do you think?
