### ISSUE TITLE
Null File paths are not ignored

### ISSUE THREAD

**Issue by tarekeldeeb** [gr2m/octokit-plugin-create-pull-request#137]
I create a PR as

```ts
  octokit
          .createPullRequest({
            owner: "..
            ...
            changes: [
              {
                files: { 
                    [this.getMandatorytFileName()]: `[${this.mandatory_value}]`,
                    [this.getOptionalFileName()]: `[${this.optional_value}]`,
                },
                commit: ..
            ...
```
The `getOptionalFileName()` may return null and an empty value.

I expect octokit to totally ignore that second null path and empty content altogether. The reality is that a file is created "null" with empty content.

Can there be a flag or an internal check to handle this use case? 

Alternatively, and more clean, is to have a `files` builder function. I find it very difficult to build the `files` list dynamically with the current strict defined types.

**Comment by gr2m** [comment]
> The reality is that a file is created "null" with empty content

This is just native JavaScript behavior

```js
const o = {[null]: 'test'}
// { null: "test" }
```

Don't set a `files` key if you don't want a file to be created
