### ISSUE TITLE
Creating binary files

### ISSUE THREAD

**Issue by pixelastic** [gr2m/octokit-plugin-create-pull-request#30]
(This issue is the follow up of [this Twitter exchange](https://twitter.com/pixelastic/status/1265923756628889601))

I'd like to use this module to create a Pull Request on a repo I own. The PR should add two jpg images to the repo (images are roughly 100-150kb in size each). I see in your current TODO `Allow to create/edit files with binary content` so I assumed this isn't yet possible.

How would you suggest I can do it using Octokit? Once I understand the steps involved, I can try to submit a PR to add the feature to this module.

So far my understanding of the steps involved without using this plugin would be:
- Create a new branch (through Octokit. Couldn't find the relevant method in the documentation)
- Add a new commit with file A ([as documented here](https://developer.github.com/v3/repos/contents/#create-or-update-a-file))
- Add a new commit with file B (same as above)
- (Maybe squash both commits together so it's cleaner)
- Create a PR from this branch

I don't have much experience with the GitHub API, nor do I know how this plugin does things internally, so this would be my naive approach to solving my current issue. Let me know if I'm heading the wrong direction and how you would have done it. Also feel free to point me to the relevant code in the current module where you think I should plug my findings.

Cheers,

**Comment by gr2m** [comment]
The implementation is a single file, I think you should be able to follow along:
https://github.com/gr2m/octokit-create-pull-request/blob/master/lib/create-pull-request.js

I've added references to the respective REST API documentation.

There is a simpler API endpoint that creates both a file and a commit: https://developer.github.com/v3/repos/contents/#create-or-update-a-file

With this plugin, I use https://developer.github.com/v3/git/trees/#create-a-tree in order to create a single commit message for multiple file updates. I think in order to support binary files, the the `tree.mode` property must be set accordingly: https://developer.github.com/v3/git/trees/#tree-object

**Comment by pixelastic** [comment]
I read the code of the plugin (thanks for the documentation links). I couldn't have written it myself without a lot of trial-and-error as the sha/tree/commit/reference dance requires some vocabulary that I was missing. 

Still, I think I understand what it's doing: you create your own tree of changed files and commit it on top of the latest commit of the repo. You then create a branch (reference) there and a PR from that branch. There was quite a lot a plumbing involved, but everything is pretty straightforward.

Now, as to implementing adding/editing of binary files, I don't think changing the `tree.mode` would be enough. It seems to only allow values for `file`, `executable`, `symlink` and `submodule`. So in theory it should already work as there is nothing that says you can't send binary content... but I guess passing raw binary data like this will surely result in garbled content.

What I think could work for binary files would be to first [create a new blob](https://developer.github.com/v3/git/blobs/#create-a-blob) for the file (by encoding its content as base64 and sending it to `POST /repos/:owner/:repo/git/blobs`). We will get a `sha` in response and we can use this `sha` key instead of the `content` key when building the custom tree. Do you think it could work?

If it does work, how do you think the public API of the module should change to accommodate this feature? It will need a way to differentiate changes to textual files from changes to binary files in the `changes.files` object because it won't treat them the same way. I was thinking of allowing passing an object `{ binary: true, base64: 'content' }` instead of the string value. 

Let me know what you think of that

Cheers,

**Comment by gr2m** [comment]
> What I think could work for binary files would be to first [create a new blob](https://developer.github.com/v3/git/blobs/#create-a-blob) for the file (by encoding its content as base64 and sending it to `POST /repos/:owner/:repo/git/blobs`). We will get a `sha` in response and we can use this `sha` key instead of the `content` key when building the custom tree. Do you think it could work?

Ah yes, I think that's what needs to be done

> how do you think the public API of the module should change to accommodate this feature

I wish we could just set the file to buffer and then check for it later, but Octokit and this plugin should work equally in Node.js and browsers, so that is not so easy. If you can think of a good way, that would be my preferred solution.

Maybe instead of `{ binary: true, base64: 'content' }` we could just do `{ base64: 'content' }`, I don't think we need the `binary` property?

Or we reuse the same properties that the [Create a blob](https://developer.github.com/v3/git/blobs/#create-a-blob) endpoint accepts: `{ content, encoding }`.

I'm not sure, and when in doubt, I prefer to stay closer to GitHub's APIs, so my vote would be for `{ content, encoding }`.

**Comment by pixelastic** [comment]
I'm not sure either. 

`{ content, encoding }` is nice because it mirror GitHub's API, but in this context it also means that people that want to edit binary files will have to manually set `{ content: "xxx", encoding: "base64" }` instead of something simple like `{ base64: 'xxx' }`. Any other encoding or no encoding would be the same as sending as text, except slower (as we'll need one additional request to get the sha). So it looks like an unnecessary burden on the user (and error-prone) where we could have handle that internally.

I'm also wondering if this new implementation (sha instead of content) should become the default implementation? We could keep backward compatibility by converting all string values to objects with no encoding, then we have only one code path for both text and binary, and this simplifies everything: we use the GitHub's API properties. The obvious downside is that we will now be making more requests where we could have grouped them into a `content` tree.

I tend to think this would be better in the long run, but this is your module and your experience, so I'll let it your call :)

**Comment by gr2m** [comment]
I think I would continue to use the existing APIs. If a string is passed, then the tree API can be continued to be used to create / update the files directly. If the new `{ content, encoding }` format is passed, then the blobs need to be created first and sha need to be passed, but only for those instances. You can use either `tree.sha` or `tree.content`, the two can be mixed in the same `POST /repos/:owner/:repo/git/trees` request

**Comment by pixelastic** [comment]
Perfect; I'll start working on that soon. Thanks for the pointers.

**Comment by pixelastic** [comment]
I created the relevant PR here: https://github.com/gr2m/octokit-create-pull-request/pull/31

**Comment by gr2m** [comment]
done via #31
