### ISSUE TITLE
Code not updating in newly created branch after a pull request

### ISSUE THREAD

**Issue by shunjid** [gr2m/octokit-plugin-create-pull-request#59]
Hi there,

You've created an awesome plugin :tada: . In one of my projects, I've been trying to use your plugin and successfully created a PR with some changes. But there is an issue.

Let's say, I haven't merged that newly created branch by your plugin and did some change again in my code. In that case, my desired change is not getting committed to the head branch. In this scenario, I'm getting some error like this below:

```
(node:2851) UnhandledPromiseRejectionWarning: HttpError: Reference already exists
    at /home/runner/work/{repo-name}/{repo-name}/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async composeCreatePullRequest (/home/runner/work/{repo-name}/{repo-name}/node_modules/octokit-plugin-create-pull-request/dist-node/index.js:281:3)
```

**My question:**
-  Does your plugin support this feature?
-  If not, do you have a plan to bring this feature soon?

Thanks :smile: ,
Have a good day !

**Comment by gr2m** [comment]
Hmm the `Reference already exists` is likely a result from trying to create a branch that already exists. I thought that we check for that, but seems we do not cover all cases.

Can you tell the steps to reproduce the problem?

**Comment by shunjid** [comment]
Hi @gr2m ,

To reproduce the problem we first need to
- Make some changes by creating a new branch
- Then we shouldn't merge/close that newly created branch
- Finally, make some changes again on the same branch without changing the `head`'s value.

Afterwards, the plugin returns `Reference already exists` and throws an error.

**Comment by gr2m** [comment]
Why did you close the issue? Did you figure out the problem?

**Comment by shunjid** [comment]
@gr2m 

Yeah. I was about to explain. There were some internet issues. Extremely sorry for late response.

In my code, I figured out that I wasn’t handling Promise in a correct way. Moreover there were some issues with caching in the environment I was running the program which were causing unexpected warning.

Once again, I wanna thank you for developing this awesome plugin. 😊
