### ISSUE TITLE
?. operated in dist-web breaks SSR

### ISSUE THREAD

**Issue by pelikhan** [gr2m/octokit-plugin-create-pull-request#68]
I'm seeing some webpack failures with the latest release due to the ?. operator.

https://github.com/gr2m/octokit-plugin-create-pull-request/blob/f2abf7fe1acdc07685306ee53069778e12080629/src/compose-create-pull-request.ts#L66

```
ERROR #98123  WEBPACK

Generating development SSR bundle failed

Unexpected token (137:29)

File:node_modules/octokit-plugin-create-pull-request/dist-web/index.js:137:29
```

**Comment by gr2m** [comment]
Make sure you use the latest `typescript` version?

**Comment by pelikhan** [comment]
I think since it's a javascript file, typescript does not rewrite index.js.

**Comment by gr2m** [comment]
Oh I see, the built JS has that syntax!

https://unpkg.com/browse/octokit-plugin-create-pull-request@3.9.2/dist-web/index.js#L137

Thank you, I'll look into it
